name: DJANGO REST CI

on:
  push:
    branches: [ feature/add-ci ]
  pull_request:
    branches: [ feature/add-ci, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set Up .env
        run: |
          echo "${{secrets.ENV_FILE}}" > shop/.env

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run DB
        run: |
          ls
          docker-compose -f docker-compose.yml up -d db

      - name: Wait for DB
        run: |
            echo "Waiting for PostgreSQL to be ready..."
            
            # Find the actual DB container ID
            DB_CONTAINER_ID=$(docker ps -q -f "name=db")
            
            if [ -z "$DB_CONTAINER_ID" ]; then
              echo "Database container not found!"
              docker ps -a  # Debugging: Show all containers
              exit 1
            fi
            
            # Wait until PostgreSQL is ready
            until docker exec -t "$DB_CONTAINER_ID" pg_isready -h localhost -p 5432 -U postgres; do
              echo "Database not ready, waiting..."
              sleep 5
            done
            
            echo "Database is ready!"

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
