name: DJANGO REST CI

on:
  push:
    branches: [ feature/add-ci ]
  pull_request:
    branches: [ feature/add-ci, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set Up .env
        run: |
          echo "${{secrets.ENV_FILE}}" > shop/.env

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run DB
        run: |
          ls
          docker-compose -f docker-compose.yml up -d db

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linter
        run: |
          prospector || true

      - name: Pytests
        run: |
          pytest
